name: notification_repo
description: A repository for handling notifications in the Gaadi Driver app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  localstorage:
    path: ../localstorage
  flutter:
    sdk: flutter
  api_client:
    path: ../api_client
  equatable: ^2.0.7
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  very_good_analysis: ^6.0.0
