name: vehicle_repo
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  api_client:
    path: ../api_client
  localstorage:
    path: ../localstorage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
